name: Run Every 5 Minutes

on:
  workflow_dispatch:

  schedule:
    # Runs every 5 minutes
    - cron: "*/5 * * * *"

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Run Script
        run: |
          echo "Workflow started"
          echo "Current time: $(date)"
          echo "Hello World"